#!/usr/bin/env bash
set -e

#This script installs required software for hosting the main CS server.

DATE=`date +%Y-%m-%d`

#First things first...
apt-get update
apt-get --assume-yes upgrade

#Install basic tools
apt-get --assume-yes --quiet install git vim 
apt-get --assume-yes --quiet install p7zip-full 
apt-get --assume-yes --quiet install aspell
apt-get --assume-yes --quiet install graphviz #Requested by Stavros

#Install gcc4.9 and others
apt-get --assume-yes --quiet install software-properties-common
if [ -f /etc/apt/sources.list.d/ubuntu-toolchain-r-test-trusty.list ];
then
  echo "Ubuntu Toolchain PPA already installed"
else
  echo "Adding Ubuntu Toolchain PPA"
  add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  apt-get update
fi
apt-get --assume-yes --quiet install gfortran build-essential

#Install pip 
if command -v pip 1>/dev/null;
then
  echo "Pip is already installed."
else
  echo "Installing pip"
  wget https://bootstrap.pypa.io/get-pip.py
  python get-pip.py 
  sudo python get-pip.py 
  rm get-pip.py
fi
pip list >> pip.list.$DATE.log

#Install python packages
# install dependencies for scipy and numpy
apt-get install -y libblas-dev liblapack-dev libevent-dev python-dev

# install dependencies for matplotlib
apt-get install -y libfreetype6-dev libpng-dev libxft-dev

# install scientific packages
pip install --quiet numpy
pip install --quiet sympy
pip install --quiet matplotlib
pip install --quiet scipy
pip install --quiet pandas

# install ipython notebook and dependencies
pip install --quiet ipython
pip install --quiet pyzmq
pip install --quiet jinja2
pip install --quiet pygments
pip install --quiet bokeh

# install FAdo for Stavros
pip install --quiet FAdo

#Install Apache2, PHP5, MySQL if they do not exist
MYSQL_ROOT_PASS="mySecretPassword"
PHPMYADMIN_DIR="secretPHPmyadmin"      #Secure phpmyadmin default install
if [ ! -f /etc/apache2/apache2.conf ];
then
  #Install Apache2 and PHP5
  apt-get --assume-yes --quiet install apache2 apache2-utils
  apt-get --assume-yes --quiet install php5 libapache2-mod-php5
  service apache2 restart

  #Enable necessary apache2 mods for per-user directories
  a2enmod php5
  a2enmod userdir 

  #Enable php access in user directories
  cp /etc/apache2/mods-enabled/php5.conf /etc/apache2/mods-enabled/php5.conf_old
  sed -i '/<IfModule mod_userdir.c>/,/<\/IfModule>/s/^/#/' /etc/apache2/mods-enabled/php5.conf

  #User directories are in /home/faculty
  cp /etc/apache2/mods-enabled/userdir.conf /etc/apache2/mods-enabled/userdir.conf_old
  sed -i '/<Directory \/home\/\*\/public_html>/s/home/home\/faculty/' \
      /etc/apache2/mods-enabled/userdir.conf
  sed -i '/<Directory \/home\/faculty\/\*\/public_html>/,/<\/Directory>/s/SymLinksIfOwnerMatch/FollowSymLinks/' \
      /etc/apache2/mods-enabled/userdir.conf
  service apache2 restart
fi

#Ensure MySQL is installed
if command -v mysql 1>/dev/null;
then
  echo "MySQL is already installed."
else
  #Load debconf with password to avoid interaction during install
  echo "mysql-server mysql-server/root_password password $MYSQL_ROOT_PASS" | debconf-set-selections
  echo "mysql-server mysql-server/root_password_again password $MYSQL_ROOT_PASS" | debconf-set-selections
  
  #Install MySQL
  apt-get --assume-yes --quiet install mysql-server
fi


#Ensure phpMyAdmin is installed
if [ ! -f /etc/phpmyadmin/config.inc.php ];
then
  #Get random data for app password (no need to record)
  AUTOGENERATED_PASS=`tr -dc A-Za-z0-9 < /dev/urandom | head -c 64`
  
  #Load debconf with password and settings to avoid interaction during install
  echo "phpmyadmin phpmyadmin/reconfigure-webserver multiselect apache2" | debconf-set-selections
  echo "phpmyadmin phpmyadmin/dbconfig-install boolean true" | debconf-set-selections
  echo "phpmyadmin phpmyadmin/mysql/admin-user string root" | debconf-set-selections
  echo "phpmyadmin phpmyadmin/mysql/admin-pass password $MYSQL_ROOT_PASS" | debconf-set-selections
  echo "phpmyadmin phpmyadmin/mysql/app-pass password $AUTOGENERATED_PASS" |debconf-set-selections
  echo "phpmyadmin phpmyadmin/app-password-confirm password $AUTOGENERATED_PASS" | debconf-set-selections
  
  #Install phpMyAdmin
  apt-get --assume-yes --quiet install phpmyadmin
  
  #Change phpMyAdmin directory
  sed -i -r "s:(Alias /).*(/usr/share/phpmyadmin):\1$PHPMYADMIN_DIR \2:" /etc/phpmyadmin/apache.conf
  
  #Manually activate mcrypt (that's an issue for Ubuntu 14.04)
  php5enmod mcrypt 
  
  service apache2 reload
fi
