# --- !Sample yaml file for testing
credentials:
  username:  'root'
  password:  'admin'
rsync_tasks_to_create:
  task0:
    rsync_mode: 'module'
    rsync_path: '/mnt/Disk1'
    rsync_remotehost: 'cs.smu.ca'
    rsync_remoteport:  22
    rsync_remotemodule: 'YamlTest2'
    rsync_remotepath:  ''
    rsync_direction: 'push'
    rsync_minute: '*'
    rsync_hour: '*'
    rsync_daymonth: '*'
    rsync_month:  '*'
    rsync_dayweek:  '*'
    rsync_desc:  ''
    rsync_delayupdates:  true
    rsync_enabled:  true
    rsync_archive:  false
    rsync_compress:  true
    rsync_extra:  ''
    rsync_quiet:  false
    rsync_recursive:  true
    rsync_times:  true
    rsync_archive:  false
    rsync_compress:  true
    rsync_extra:  ''
    rsync_quiet:  false
    rsync_recursive: true
    rsync_times:  true
rsync_tasks_to_update:
  task0:
    id:  1
rsync_tasks_to_delete:
  task0:
    id:  1
