# --- !Sample yaml file for testing
credentials:
  username:  'root'
  password:  'admin'
# Run this as a test, there should be 1 task named UpdatedTaskName
rsync_tasks:
    to_create:
      0:
        rsync_mode: 'module'
        rsync_path: '/mnt/Disk'
        rsync_remotehost: 'cs.smu.ca'
        rsync_remoteport:  22
        rsync_remotemodule: 'TestTask1'
        rsync_remotepath:  ''
        rsync_direction: 'push'
        rsync_minute: '*'
        rsync_hour: '*'
        rsync_daymonth: '*'
        rsync_month:  '*'
        rsync_dayweek:  '*'
        rsync_desc:  ''
        rsync_delayupdates:  true
        rsync_enabled:  true
        rsync_archive:  false
        rsync_compress:  true
        rsync_extra:  ''
        rsync_quiet:  false
        rsync_recursive:  true
        rsync_times:  true
      1:
        rsync_mode: 'module'
        rsync_path: '/mnt/Disk'
        rsync_remotehost: 'cs.smu.ca'
        rsync_remoteport:  22
        rsync_remotemodule: 'TestTask2'
        rsync_remotepath:  ''
        rsync_direction: 'push'
        rsync_minute: '*'
        rsync_hour: '*'
        rsync_daymonth: '*'
        rsync_month:  '*'
        rsync_dayweek:  '*'
        rsync_desc:  ''
        rsync_delayupdates:  true
        rsync_enabled:  true
        rsync_archive:  false
        rsync_compress:  true
        rsync_extra:  ''
        rsync_quiet:  false
        rsync_recursive:  true
        rsync_times:  true  
      2:
        rsync_mode: 'module'
        rsync_path: '/mnt/Disk'
        rsync_remotehost: 'cs.smu.ca'
        rsync_remoteport:  22
        rsync_remotemodule: 'TestTask3'
        rsync_remotepath:  ''
        rsync_direction: 'push'
        rsync_minute: '*'
        rsync_hour: '*'
        rsync_daymonth: '*'
        rsync_month:  '*'
        rsync_dayweek:  '*'
        rsync_desc:  ''
        rsync_delayupdates:  true
        rsync_enabled:  true
        rsync_archive:  false
        rsync_compress:  true
        rsync_extra:  ''
        rsync_quiet:  false
        rsync_recursive:  true
        rsync_times:  true
    to_update:
      0:
        id:  1
        rsync_mode: 'module'
        rsync_path: '/mnt/Disk'
        rsync_remotehost: 'cs.smu.ca'
        rsync_remoteport:  22
        rsync_remotemodule: 'UpdatedTaskName'
        rsync_remotepath:  ''
        rsync_direction: 'push'
        rsync_minute: '*'
        rsync_hour: '*'
        rsync_daymonth: '*'
        rsync_month:  '*'
        rsync_dayweek:  '*'
        rsync_desc:  ''
        rsync_delayupdates:  false
        rsync_enabled:  true
        rsync_archive:  true
        rsync_compress:  false
        rsync_extra:  ''
        rsync_quiet:  false
        rsync_recursive:  false
        rsync_times:  true
    to_delete:
      0:
        id:  2
      1:
        id:  3



