#!/usr/bin/env bash
set -e

#This script installs required software for hosting the CDA5540 course.
#This includes a full LAMP stack plus MongoDB

MYSQL_ROOT_PASS="mySecretPassword"
PHPMYADMIN_DIR="secretPHPmyadmin"      #Secure phpmyadmin default install

#Set hostname
NEW_HOSTNAME=cda540
hostnamectl set-hostname $NEW_HOSTNAME
sed -i 's/127.0.1.1.*/127.0.1.1\t'"$NEW_HOSTNAME"'/g' /etc/hosts

#Get and apply any updates
apt-get update
apt-get --assume-yes upgrade

#Install basic tools
apt-get --assume-yes --quiet install git vim ethtool iperf p7zip-full aspell ispell finger software-properties-common graphviz

#Install Oracle Java 8
apt-add-repository ppa:webupd8team/java
apt-get update
apt-get install oracle-java8-installer

#Install gcc5 and others
if [ -f /etc/apt/sources.list.d/ubuntu-toolchain-r-test-trusty.list ];
then
  echo "Ubuntu Toolchain PPA already installed"
else
  echo "Adding Ubuntu Toolchain PPA"
  add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  apt-get update
fi
apt-get --assume-yes --quiet install gcc-5 build-essential

#Install pip 
if command -v pip 1>/dev/null;
then
  echo "Pip is already installed."
else
  echo "Installing pip"
  wget https://bootstrap.pypa.io/get-pip.py
  python get-pip.py 
  sudo python get-pip.py 
  rm get-pip.py
fi
pip list >> pip.list.$DATE.log

#Install python packages
# install dependencies for scipy and numpy
apt-get install -y libblas-dev liblapack-dev libevent-dev python-dev

# install dependencies for matplotlib
apt-get install -y libfreetype6-dev libpng-dev libxft-dev

# install scientific packages
pip install --quiet numpy
pip install --quiet sympy
pip install --quiet matplotlib
pip install --quiet scipy
pip install --quiet pandas

# install ipython notebook and dependencies
pip install --quiet ipython
pip install --quiet pyzmq
pip install --quiet jinja2
pip install --quiet pygments
pip install --quiet bokeh

# install other python libraries
pip install --quiet pymongo


#Install Apache2, PHP5, MySQL if they do not exist
if [ ! -f /etc/apache2/apache2.conf ];
then
  #Install Apache2 and PHP5
  apt-get --assume-yes install apache2 apache2-utils
  apt-get --assume-yes install php5 libapache2-mod-php5
  service apache2 restart

  #Enable necessary apache2 mods for per-user directories
  a2enmod php5
  a2enmod userdir 

  #Enable php access in user directories
  cp /etc/apache2/mods-enabled/php5.conf /etc/apache2/mods-enabled/php5.conf_old
  sed -i '/<IfModule mod_userdir.c>/,/<\/IfModule>/s/^/#/' /etc/apache2/mods-enabled/php5.conf

  #User directories are in /home/course/cda540/
  cp /etc/apache2/mods-enabled/userdir.conf /etc/apache2/mods-enabled/userdir.conf_old
  sed -i '/<Directory \/home\/\*\/public_html>/s/home/home\/course\/cda540/' \
      /etc/apache2/mods-enabled/userdir.conf
  sed -i '/<Directory \/home\/course\/cda540\/\*\/public_html>/,/<\/Directory>/s/SymLinksIfOwnerMatch/FollowSymLinks/' \
      /etc/apache2/mods-enabled/userdir.conf
  service apache2 restart

  #Install MySQL with preconfigured password
  echo "mysql-server mysql-server/root_password password $MYSQL_ROOT_PASS" | debconf-set-selections
  echo "mysql-server mysql-server/root_password_again password $MYSQL_ROOT_PASS" | debconf-set-selections
  
  apt-get --assume-yes install mysql-server
fi


#Install phpmyadmin
if [ ! -f /etc/phpmyadmin/config.inc.php ];
then
  #Get random data for app password
  AUTOGENERATED_PASS=`tr -dc A-Za-z0-9 < /dev/urandom | head -c 64`
  
  echo "phpmyadmin phpmyadmin/reconfigure-webserver multiselect apache2" | debconf-set-selections
  echo "phpmyadmin phpmyadmin/dbconfig-install boolean true" | debconf-set-selections
  echo "phpmyadmin phpmyadmin/mysql/admin-user string root" | debconf-set-selections
  echo "phpmyadmin phpmyadmin/mysql/admin-pass password $MYSQL_ROOT_PASS" | debconf-set-selections
  echo "phpmyadmin phpmyadmin/mysql/app-pass password $AUTOGENERATED_PASS" |debconf-set-selections
  echo "phpmyadmin phpmyadmin/app-password-confirm password $AUTOGENERATED_PASS" | debconf-set-selections
  
  apt-get --assume-yes install phpmyadmin
  
  #Change phpMyAdmin directory
  sed -i -r "s:(Alias /).*(/usr/share/phpmyadmin):\1$PHPMYADMIN_DIR \2:" /etc/phpmyadmin/apache.conf
  
  php5enmod mcrypt # Needs to be activated manually (that's an issue for Ubuntu 14.04)
  
  service apache2 reload
fi


#Install Mongodb
if [ ! -f /usr/bin/mongod ];
then
  #Increase appropriate limits for database usage
  ulimit -n 64000
  ulimit -u 64000

  #Install MongoDB from mongo's packages
  sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
  echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list
  sudo apt-get update
  apt-get --assume-yes --quiet install mongodb-org
fi
