#!/bin/bash
#This script installs required software for hosting the CSCI2355 course.

apt-get update
apt-get --assume-yes upgrade

#Install basic tools
apt-get --assume-yes --quiet install git vim ethtool iperf p7zip-full aspell ispell finger

MYSQL_ROOT_PASS="mySecretPassword"
PHPMYADMIN_DIR="secretPHPmyadmin"      #Secure phpmyadmin default install

#Install Apache2, PHP5, MySQL if they do not exist
if [ ! -f /etc/apache2/apache2.conf ];
then
  #Install Apache2 and PHP5
  apt-get --assume-yes install apache2 apache2-utils
  apt-get --assume-yes install php5 libapache2-mod-php5
  service apache2 restart

  #Enable necessary apache2 mods for per-user directories
  a2enmod php5
  a2enmod userdir 

  #Enable php access in user directories
  cp /etc/apache2/mods-enabled/php5.conf /etc/apache2/mods-enabled/php5.conf_old
  sed -i '/<IfModule mod_userdir.c>/,/<\/IfModule>/s/^/#/' /etc/apache2/mods-enabled/php5.conf

  #User directories are in /home/course/csc355/
  cp /etc/apache2/mods-enabled/userdir.conf /etc/apache2/mods-enabled/userdir.conf_old
  sed -i '/<Directory \/home\/\*\/public_html>/s/home/home\/course\/csc355/' \
      /etc/apache2/mods-enabled/userdir.conf
  sed -i '/<Directory \/home\/course\/csc355\/\*\/public_html>/,/<\/Directory>/s/SymLinksIfOwnerMatch/FollowSymLinks/' \
      /etc/apache2/mods-enabled/userdir.conf
  service apache2 restart

  #Install MySQL with preconfigured password
  echo "mysql-server mysql-server/root_password password $MYSQL_ROOT_PASS" | debconf-set-selections
  echo "mysql-server mysql-server/root_password_again password $MYSQL_ROOT_PASS" | debconf-set-selections
  
  #MySQL: Make sure loopback device has IP (needed for mysql install)
  ip addr add 127.0.0.1 dev lo
  
  apt-get --assume-yes install mysql-server
fi


#Install phpmyadmin
if [ ! -f /etc/phpmyadmin/config.inc.php ];
then
  #Get random data for app password
  AUTOGENERATED_PASS=`tr -dc A-Za-z0-9 < /dev/urandom | head -c 64`
  
  echo "phpmyadmin phpmyadmin/reconfigure-webserver multiselect apache2" | debconf-set-selections
  echo "phpmyadmin phpmyadmin/dbconfig-install boolean true" | debconf-set-selections
  echo "phpmyadmin phpmyadmin/mysql/admin-user string root" | debconf-set-selections
  echo "phpmyadmin phpmyadmin/mysql/admin-pass password $MYSQL_ROOT_PASS" | debconf-set-selections
  echo "phpmyadmin phpmyadmin/mysql/app-pass password $AUTOGENERATED_PASS" |debconf-set-selections
  echo "phpmyadmin phpmyadmin/app-password-confirm password $AUTOGENERATED_PASS" | debconf-set-selections
  
  apt-get --assume-yes install phpmyadmin
  
  #Change phpMyAdmin directory
  sed -i -r "s:(Alias /).*(/usr/share/phpmyadmin):\1$PHPMYADMIN_DIR \2:" /etc/phpmyadmin/apache.conf
  
  php5enmod mcrypt # Needs to be activated manually (that's an issue for Ubuntu 14.04)
  
  service apache2 reload
fi
